[package]
name = "ringbuf"
version = "0.2.6"
authors = ["Alexey Gerasev <alexey.gerasev@gmail.com>"]
edition = "2018"

description = "Lock-free SPSC FIFO ring buffer with direct access to inner data"
documentation = "https://docs.rs/ringbuf"
homepage = "https://github.com/nthend/ringbuf"
repository = "https://github.com/nthend/ringbuf.git"
readme = "README.md"
keywords = ["lock-free", "spsc", "ring-buffer", "rb", "fifo"]
categories = ["concurrency", "data-structures", "no-std"]
license = "MIT/Apache-2.0"

[features]
default = ["std"]
std = []
benchmark = []
reader-sleep-copy = []
writer-sleep-copy = []

[[example]]
name = "simple"
[[example]]
name = "message"
required-features = ["std"]

[dependencies]
cache-padded = "1.1.1"
sync_spin = { path = './sync_spin' }
